### ISSUE TITLE
Override config from command line

### ISSUE THREAD

**Issue by gabrielmontagne** [ifrost/afterwriting-labs#112]
This project is great. Amazing stuff.

I'm switching from a clunky fountain -> LaTeX -> pdf workflow to this.  I love it!

But it'd be great if elements from the config file could be overriden as command line arguments, for example, title page notes, watermarks, etc. for versions and dates.  A bit like asciidoc(tor) does, `-a, --attribute=ATTRIBUTE` . 

This would help a lot on `Makefile` type workflows like mine.

**Comment by gabrielmontagne** [comment]
Could be done, as well, using environment variables.

**Comment by ifrost** [comment]
It's available in version 1.12.5 (https://www.npmjs.com/package/afterwriting/v/1.12.5). Please check README for usage.

**Comment by rnkn** [comment]
This is great news. Love your work.

**Comment by rnkn** [comment]
Just wanted to add that I’m in the process of making afterwriting the default export option for Fountain Mode for Emacs, and having these CLI switches make for a much nicer/smoother user experience in my view:

![Screen Shot 2020-01-14 at 1 02 55 pm](https://user-images.githubusercontent.com/1256849/72311208-a6a23580-36cf-11ea-9e69-6d42544a0179.png)

May I ask why you opted for `--setting ATTRIBUTE=VALUE` rather than `--ATTRIBUTE=VALUE`? I assume there’s a technical reason so I’m just curious...
